version: "3.3"
services:
  app:
    image: university
    container_name: university
    ports:
        - "8888:8080"
    restart: always
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/university
        SPRING_DATASOURCE_USERNAME: user_university
        SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
        - postgres
    links:
        - postgres
  postgres:
    image: postgres:13.5-alpine
    container_name: postgres
    expose:
        - "5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
    restart: unless-stopped
    volumes: 
        - ./dockerfiles/postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak_db
        DB_USER: keycloak_user
        DB_SCHEMA: public
        DB_PASSWORD: keycloak
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
    ports:
        - "8084:8080"
    depends_on:
        - postgres
    restart: unless-stopped
    links:
        - postgres
