DROP TABLE IF EXISTS LESSONS;
DROP TABLE IF EXISTS GROUPS_STUDENTS;
DROP TABLE IF EXISTS STUDENTS;
DROP TABLE IF EXISTS COURSES;
DROP TABLE IF EXISTS TEACHERS;
DROP TABLE IF EXISTS GROUPS;
DROP TABLE IF EXISTS CLASSROOMS;
CREATE TABLE TEACHERS (id BIGSERIAL PRIMARY KEY, firstname varchar(100), lastname varchar(100));
CREATE TABLE COURSES (id BIGSERIAL PRIMARY KEY, name varchar(100), teacher int REFERENCES TEACHERS(id) ON DELETE CASCADE);
CREATE TABLE STUDENTS (id BIGSERIAL PRIMARY KEY, firstname varchar(100), lastname varchar(100), UNIQUE (firstname,lastname));
CREATE TABLE GROUPS (id BIGSERIAL PRIMARY KEY, name varchar(10));
CREATE TABLE GROUPS_STUDENTS (group_id int NOT NULL REFERENCES groups(id) ON DELETE CASCADE, student_id int NOT NULL REFERENCES students(id) ON DELETE CASCADE, CONSTRAINT groups_students_pkey PRIMARY KEY (group_id, student_id));
CREATE TABLE CLASSROOMS (id BIGSERIAL PRIMARY KEY, name varchar(10));
CREATE TABLE LESSONS (id BIGSERIAL PRIMARY KEY, group_id int REFERENCES GROUPS(id) ON DELETE CASCADE, course int REFERENCES COURSES(id) ON DELETE CASCADE, classroom int REFERENCES CLASSROOMS(id) ON DELETE CASCADE, starttime bigint NOT NULL, duration bigint NOT NULL);
INSERT INTO students (firstname, lastname) VALUES ('Abbey','Wilkes');
INSERT INTO students (firstname, lastname) VALUES ('Bernice','Bone');
INSERT INTO students (firstname, lastname) VALUES ('Cecelia','Ferreira');
INSERT INTO students (firstname, lastname) VALUES ('Natan','Valencia');
INSERT INTO students (firstname, lastname) VALUES ('Olivia','Fitzpatrick');
INSERT INTO students (firstname, lastname) VALUES ('Aimie','Morrow');
INSERT INTO students (firstname, lastname) VALUES ('Joel','West');
INSERT INTO students (firstname, lastname) VALUES ('Lola-Mae','Mac');
INSERT INTO students (firstname, lastname) VALUES ('Jaxx','Hahn');
INSERT INTO students (firstname, lastname) VALUES ('Emma','Byrd');
INSERT INTO students (firstname, lastname) VALUES ('Blythe','Guthrie');
INSERT INTO students (firstname, lastname) VALUES ('Ocean','Roberson');
INSERT INTO students (firstname, lastname) VALUES ('Jac','Crosby');
INSERT INTO students (firstname, lastname) VALUES ('Kadeem','Vance');
INSERT INTO students (firstname, lastname) VALUES ('Michalina','Shannon');
INSERT INTO students (firstname, lastname) VALUES ('Davey','Hume');
INSERT INTO students (firstname, lastname) VALUES ('Faheem','Cox');
INSERT INTO students (firstname, lastname) VALUES ('Eden','Keeling');
INSERT INTO students (firstname, lastname) VALUES ('Tasnia','Glass');
INSERT INTO students (firstname, lastname) VALUES ('Coby','Barlow');
INSERT INTO students (firstname, lastname) VALUES ('Devante','Rosario');
INSERT INTO students (firstname, lastname) VALUES ('Jovan','Rhodes');
INSERT INTO students (firstname, lastname) VALUES ('Tomi','Ridley');
INSERT INTO students (firstname, lastname) VALUES ('Danish','Philip');
INSERT INTO students (firstname, lastname) VALUES ('Fiona','Mill');
INSERT INTO students (firstname, lastname) VALUES ('Matylda','Rosas');
INSERT INTO students (firstname, lastname) VALUES ('Alessia','Huffman');
INSERT INTO students (firstname, lastname) VALUES ('Nell','Wilkerson');
INSERT INTO students (firstname, lastname) VALUES ('Miranda','Shelton');
INSERT INTO students (firstname, lastname) VALUES ('Harvey-Lee','Duffy');
INSERT INTO students (firstname, lastname) VALUES ('Artur','Hook');
INSERT INTO students (firstname, lastname) VALUES ('Isaac','Laing');
INSERT INTO students (firstname, lastname) VALUES ('Aled','Marin');
INSERT INTO students (firstname, lastname) VALUES ('Shantelle','Ochoa');
INSERT INTO students (firstname, lastname) VALUES ('Etienne','Xiong');
INSERT INTO students (firstname, lastname) VALUES ('Andy','Wilson');
INSERT INTO students (firstname, lastname) VALUES ('Ruby','Hammond');
INSERT INTO students (firstname, lastname) VALUES ('Eshaal','Novak');
INSERT INTO students (firstname, lastname) VALUES ('Aedan','North');
INSERT INTO students (firstname, lastname) VALUES ('Isra','Allan');
INSERT INTO students (firstname, lastname) VALUES ('Isla-Rae','Davis');
INSERT INTO students (firstname, lastname) VALUES ('Victoria','Barajas');
INSERT INTO students (firstname, lastname) VALUES ('Frances','Mcgregor');
INSERT INTO students (firstname, lastname) VALUES ('Kenny','Mckeown');
INSERT INTO students (firstname, lastname) VALUES ('Haniya','Watson');
INSERT INTO students (firstname, lastname) VALUES ('Kiah','Farrington');
INSERT INTO students (firstname, lastname) VALUES ('Izzie','Carrillo');
INSERT INTO students (firstname, lastname) VALUES ('Alysia','Russell');
INSERT INTO students (firstname, lastname) VALUES ('Sabina','Barker');
INSERT INTO students (firstname, lastname) VALUES ('Aida','Weir');
INSERT INTO students (firstname, lastname) VALUES ('Glenda','Bond');
INSERT INTO students (firstname, lastname) VALUES ('River','Mcguire');
INSERT INTO students (firstname, lastname) VALUES ('Shaurya','Moran');
INSERT INTO students (firstname, lastname) VALUES ('Delilah','Terry');
INSERT INTO students (firstname, lastname) VALUES ('Milo','Whyte');
INSERT INTO students (firstname, lastname) VALUES ('Safiyyah','Mccarty');
INSERT INTO students (firstname, lastname) VALUES ('Livia','Lucero');
INSERT INTO students (firstname, lastname) VALUES ('Albie','Christensen');
INSERT INTO students (firstname, lastname) VALUES ('Nisha','Winters');
INSERT INTO students (firstname, lastname) VALUES ('Jillian','Tomlinson');
INSERT INTO students (firstname, lastname) VALUES ('Ksawery','Osborn');
INSERT INTO students (firstname, lastname) VALUES ('Huda','Compton');
INSERT INTO students (firstname, lastname) VALUES ('Sian','Gould');
INSERT INTO students (firstname, lastname) VALUES ('Sheridan','Esquivel');
INSERT INTO students (firstname, lastname) VALUES ('Anees','Quinn');
INSERT INTO students (firstname, lastname) VALUES ('Kornelia','Rose');
INSERT INTO students (firstname, lastname) VALUES ('Yousif','Clements');
INSERT INTO students (firstname, lastname) VALUES ('Naomi','Hamilton');
INSERT INTO students (firstname, lastname) VALUES ('Kasey','Serrano');
INSERT INTO students (firstname, lastname) VALUES ('Cathal','Stephens');
INSERT INTO students (firstname, lastname) VALUES ('Tehya','Douglas');
INSERT INTO students (firstname, lastname) VALUES ('Marisa','Garrett');
INSERT INTO students (firstname, lastname) VALUES ('Carrie','Briggs');
INSERT INTO students (firstname, lastname) VALUES ('Caio','Blevins');
INSERT INTO students (firstname, lastname) VALUES ('Ann','Carpenter');
INSERT INTO students (firstname, lastname) VALUES ('Farhana','Brennan');
INSERT INTO students (firstname, lastname) VALUES ('Lillie-May','Ho');
INSERT INTO students (firstname, lastname) VALUES ('Ariana','Hoffman');
INSERT INTO students (firstname, lastname) VALUES ('Shakira','Santos');
INSERT INTO students (firstname, lastname) VALUES ('Leen','Salgado');
INSERT INTO students (firstname, lastname) VALUES ('Misty','Mcbride');
INSERT INTO students (firstname, lastname) VALUES ('Amaya','Vo');
INSERT INTO students (firstname, lastname) VALUES ('Jannah','Moore');
INSERT INTO students (firstname, lastname) VALUES ('Kelsey','Cowan');
INSERT INTO students (firstname, lastname) VALUES ('Elleanor','Finch');
INSERT INTO students (firstname, lastname) VALUES ('Niyah','Guerra');
INSERT INTO students (firstname, lastname) VALUES ('Craig','Donald');
INSERT INTO students (firstname, lastname) VALUES ('Asma','Frost');
INSERT INTO students (firstname, lastname) VALUES ('Jawad','Carroll');
INSERT INTO students (firstname, lastname) VALUES ('Lincoln','Burn');
INSERT INTO students (firstname, lastname) VALUES ('Herman','Rangel');
INSERT INTO students (firstname, lastname) VALUES ('Presley','Mendoza');
INSERT INTO students (firstname, lastname) VALUES ('Jazmine','Paterson');
INSERT INTO students (firstname, lastname) VALUES ('Bradley','York');
INSERT INTO students (firstname, lastname) VALUES ('Fred','Harding');
INSERT INTO students (firstname, lastname) VALUES ('Mysha','Bowers');
INSERT INTO students (firstname, lastname) VALUES ('Erica','Corbett');
INSERT INTO students (firstname, lastname) VALUES ('Khadeejah','Gordon');
INSERT INTO students (firstname, lastname) VALUES ('Miya','Blake');
INSERT INTO groups (name) VALUES ('AB-101');
INSERT INTO groups (name) VALUES ('AB-201');
INSERT INTO groups (name) VALUES ('AB-301');
INSERT INTO groups (name) VALUES ('AB-401');
INSERT INTO groups (name) VALUES ('AB-501');
INSERT INTO groups (name) VALUES ('CD-101');
INSERT INTO groups (name) VALUES ('CD-201');
INSERT INTO groups (name) VALUES ('CD-301');
INSERT INTO groups (name) VALUES ('CD-401');
INSERT INTO groups (name) VALUES ('CD-501');
INSERT INTO groups_students (group_id,student_id) VALUES(1,1);
INSERT INTO groups_students (group_id,student_id) VALUES(1,2);
INSERT INTO groups_students (group_id,student_id) VALUES(1,3);
INSERT INTO groups_students (group_id,student_id) VALUES(1,4);
INSERT INTO groups_students (group_id,student_id) VALUES(1,5);
INSERT INTO groups_students (group_id,student_id) VALUES(1,6);
INSERT INTO groups_students (group_id,student_id) VALUES(1,7);
INSERT INTO groups_students (group_id,student_id) VALUES(1,8);
INSERT INTO groups_students (group_id,student_id) VALUES(1,9);
INSERT INTO groups_students (group_id,student_id) VALUES(1,10);
INSERT INTO groups_students (group_id,student_id) VALUES(2,11);
INSERT INTO groups_students (group_id,student_id) VALUES(2,12);
INSERT INTO groups_students (group_id,student_id) VALUES(2,13);
INSERT INTO groups_students (group_id,student_id) VALUES(2,14);
INSERT INTO groups_students (group_id,student_id) VALUES(2,15);
INSERT INTO groups_students (group_id,student_id) VALUES(2,16);
INSERT INTO groups_students (group_id,student_id) VALUES(2,17);
INSERT INTO groups_students (group_id,student_id) VALUES(2,18);
INSERT INTO groups_students (group_id,student_id) VALUES(2,19);
INSERT INTO groups_students (group_id,student_id) VALUES(2,20);
INSERT INTO groups_students (group_id,student_id) VALUES(3,21);
INSERT INTO groups_students (group_id,student_id) VALUES(3,22);
INSERT INTO groups_students (group_id,student_id) VALUES(3,23);
INSERT INTO groups_students (group_id,student_id) VALUES(3,24);
INSERT INTO groups_students (group_id,student_id) VALUES(3,25);
INSERT INTO groups_students (group_id,student_id) VALUES(3,26);
INSERT INTO groups_students (group_id,student_id) VALUES(3,27);
INSERT INTO groups_students (group_id,student_id) VALUES(3,28);
INSERT INTO groups_students (group_id,student_id) VALUES(3,29);
INSERT INTO groups_students (group_id,student_id) VALUES(3,30);
INSERT INTO groups_students (group_id,student_id) VALUES(4,31);
INSERT INTO groups_students (group_id,student_id) VALUES(4,32);
INSERT INTO groups_students (group_id,student_id) VALUES(4,33);
INSERT INTO groups_students (group_id,student_id) VALUES(4,34);
INSERT INTO groups_students (group_id,student_id) VALUES(4,35);
INSERT INTO groups_students (group_id,student_id) VALUES(4,36);
INSERT INTO groups_students (group_id,student_id) VALUES(4,37);
INSERT INTO groups_students (group_id,student_id) VALUES(4,38);
INSERT INTO groups_students (group_id,student_id) VALUES(4,39);
INSERT INTO groups_students (group_id,student_id) VALUES(4,40);
INSERT INTO groups_students (group_id,student_id) VALUES(5,41);
INSERT INTO groups_students (group_id,student_id) VALUES(5,42);
INSERT INTO groups_students (group_id,student_id) VALUES(5,43);
INSERT INTO groups_students (group_id,student_id) VALUES(5,44);
INSERT INTO groups_students (group_id,student_id) VALUES(5,45);
INSERT INTO groups_students (group_id,student_id) VALUES(5,46);
INSERT INTO groups_students (group_id,student_id) VALUES(5,47);
INSERT INTO groups_students (group_id,student_id) VALUES(5,48);
INSERT INTO groups_students (group_id,student_id) VALUES(5,49);
INSERT INTO groups_students (group_id,student_id) VALUES(5,50);
INSERT INTO groups_students (group_id,student_id) VALUES(6,51);
INSERT INTO groups_students (group_id,student_id) VALUES(6,52);
INSERT INTO groups_students (group_id,student_id) VALUES(6,53);
INSERT INTO groups_students (group_id,student_id) VALUES(6,54);
INSERT INTO groups_students (group_id,student_id) VALUES(6,55);
INSERT INTO groups_students (group_id,student_id) VALUES(6,56);
INSERT INTO groups_students (group_id,student_id) VALUES(6,57);
INSERT INTO groups_students (group_id,student_id) VALUES(6,58);
INSERT INTO groups_students (group_id,student_id) VALUES(6,59);
INSERT INTO groups_students (group_id,student_id) VALUES(6,60);
INSERT INTO groups_students (group_id,student_id) VALUES(7,61);
INSERT INTO groups_students (group_id,student_id) VALUES(7,62);
INSERT INTO groups_students (group_id,student_id) VALUES(7,63);
INSERT INTO groups_students (group_id,student_id) VALUES(7,64);
INSERT INTO groups_students (group_id,student_id) VALUES(7,65);
INSERT INTO groups_students (group_id,student_id) VALUES(7,66);
INSERT INTO groups_students (group_id,student_id) VALUES(7,67);
INSERT INTO groups_students (group_id,student_id) VALUES(7,68);
INSERT INTO groups_students (group_id,student_id) VALUES(7,69);
INSERT INTO groups_students (group_id,student_id) VALUES(7,70);
INSERT INTO groups_students (group_id,student_id) VALUES(8,71);
INSERT INTO groups_students (group_id,student_id) VALUES(8,72);
INSERT INTO groups_students (group_id,student_id) VALUES(8,73);
INSERT INTO groups_students (group_id,student_id) VALUES(8,74);
INSERT INTO groups_students (group_id,student_id) VALUES(8,75);
INSERT INTO groups_students (group_id,student_id) VALUES(8,76);
INSERT INTO groups_students (group_id,student_id) VALUES(8,77);
INSERT INTO groups_students (group_id,student_id) VALUES(8,78);
INSERT INTO groups_students (group_id,student_id) VALUES(8,79);
INSERT INTO groups_students (group_id,student_id) VALUES(8,80);
INSERT INTO groups_students (group_id,student_id) VALUES(9,81);
INSERT INTO groups_students (group_id,student_id) VALUES(9,82);
INSERT INTO groups_students (group_id,student_id) VALUES(9,83);
INSERT INTO groups_students (group_id,student_id) VALUES(9,84);
INSERT INTO groups_students (group_id,student_id) VALUES(9,85);
INSERT INTO groups_students (group_id,student_id) VALUES(9,86);
INSERT INTO groups_students (group_id,student_id) VALUES(9,87);
INSERT INTO groups_students (group_id,student_id) VALUES(9,88);
INSERT INTO groups_students (group_id,student_id) VALUES(9,89);
INSERT INTO groups_students (group_id,student_id) VALUES(9,90);
INSERT INTO groups_students (group_id,student_id) VALUES(10,91);
INSERT INTO groups_students (group_id,student_id) VALUES(10,92);
INSERT INTO groups_students (group_id,student_id) VALUES(10,93);
INSERT INTO groups_students (group_id,student_id) VALUES(10,94);
INSERT INTO groups_students (group_id,student_id) VALUES(10,95);
INSERT INTO groups_students (group_id,student_id) VALUES(10,96);
INSERT INTO groups_students (group_id,student_id) VALUES(10,97);
INSERT INTO groups_students (group_id,student_id) VALUES(10,98);
INSERT INTO groups_students (group_id,student_id) VALUES(10,99);
INSERT INTO teachers (firstname, lastname) VALUES ('Bradleigh','Donaldson');
INSERT INTO teachers (firstname, lastname) VALUES ('Minahil','Heath');
INSERT INTO teachers (firstname, lastname) VALUES ('Garry','Mclellan');
INSERT INTO teachers (firstname, lastname) VALUES ('Anand','Whittington');
INSERT INTO teachers (firstname, lastname) VALUES ('Ioana','Ellwood');
INSERT INTO teachers (firstname, lastname) VALUES ('Odin','Combs');
INSERT INTO teachers (firstname, lastname) VALUES ('Jonas','Huang');
INSERT INTO teachers (firstname, lastname) VALUES ('Devonte','Appleton');
INSERT INTO teachers (firstname, lastname) VALUES ('Flynn','Michael');
INSERT INTO teachers (firstname, lastname) VALUES ('Wanda','Sherman');
INSERT INTO teachers (firstname, lastname) VALUES ('Stefania','Kelley');
INSERT INTO teachers (firstname, lastname) VALUES ('Junior','Tillman');
INSERT INTO teachers (firstname, lastname) VALUES ('Micah','Cowan');
INSERT INTO teachers (firstname, lastname) VALUES ('Chelsea','Clay');
INSERT INTO teachers (firstname, lastname) VALUES ('Manisha','Sykes');
INSERT INTO teachers (firstname, lastname) VALUES ('Nataniel','Kent');
INSERT INTO teachers (firstname, lastname) VALUES ('Miley','Maddox');
INSERT INTO teachers (firstname, lastname) VALUES ('Yuvaan','Dickerson');
INSERT INTO teachers (firstname, lastname) VALUES ('Xander','Kirkpatrick');
INSERT INTO teachers (firstname, lastname) VALUES ('Avleen','Cochran');
INSERT INTO courses (name, teacher) VALUES ('Advertising business',1);
INSERT INTO courses (name, teacher) VALUES ('Management',2);
INSERT INTO courses (name, teacher) VALUES ('Communications',3);
INSERT INTO courses (name, teacher) VALUES ('English',4);
INSERT INTO courses (name, teacher) VALUES ('Marketing',5);
INSERT INTO courses (name, teacher) VALUES ('Media Studies',6);
INSERT INTO courses (name, teacher) VALUES ('Graphic Design',7);
INSERT INTO courses (name, teacher) VALUES ('Fine Art',8);
INSERT INTO courses (name, teacher) VALUES ('Hospitality management',9);
INSERT INTO courses (name, teacher) VALUES ('Leisure and Tourism',10);
INSERT INTO courses (name, teacher) VALUES ('Building management',11);
INSERT INTO courses (name, teacher) VALUES ('Business Studies',12);
INSERT INTO courses (name, teacher) VALUES ('Construction Technology',13);
INSERT INTO courses (name, teacher) VALUES ('Archaeology',14);
INSERT INTO courses (name, teacher) VALUES ('Social Education',15);
INSERT INTO courses (name, teacher) VALUES ('Geography',16);
INSERT INTO courses (name, teacher) VALUES ('Museum Studies',17);
INSERT INTO courses (name, teacher) VALUES ('History',18);
INSERT INTO classrooms (name) VALUES ('ROOM-1');
INSERT INTO classrooms (name) VALUES ('ROOM-2');
INSERT INTO classrooms (name) VALUES ('ROOM-3');
INSERT INTO classrooms (name) VALUES ('ROOM-4');
INSERT INTO classrooms (name) VALUES ('ROOM-5');
INSERT INTO classrooms (name) VALUES ('ROOM-6');
INSERT INTO classrooms (name) VALUES ('ROOM-7');
INSERT INTO classrooms (name) VALUES ('ROOM-8');
INSERT INTO classrooms (name) VALUES ('ROOM-9');
INSERT INTO classrooms (name) VALUES ('ROOM-10');
INSERT INTO classrooms (name) VALUES ('ROOM-11');
INSERT INTO classrooms (name) VALUES ('ROOM-12');
INSERT INTO classrooms (name) VALUES ('ROOM-13');
INSERT INTO classrooms (name) VALUES ('ROOM-14');
INSERT INTO classrooms (name) VALUES ('ROOM-15');
INSERT INTO classrooms (name) VALUES ('ROOM-16');
INSERT INTO classrooms (name) VALUES ('ROOM-17');
INSERT INTO lessons (group_id,course,classroom,starttime,duration) VALUES (1,1,1,1616510000000,2700000);
INSERT INTO lessons (group_id,course,classroom,starttime,duration) VALUES (2,2,2,1616510000000,3600000);