INSERT INTO students (firstname, lastname) VALUES ('John', 'Davidson');
INSERT INTO students (firstname, lastname) VALUES ('Nick', 'Johnson');
INSERT INTO students (firstname, lastname) VALUES ('Peter', 'Eastwood');
INSERT INTO students (firstname, lastname) VALUES ('Michael', 'Murray');
INSERT INTO students (firstname, lastname) VALUES ('Mike', 'Dombrovsky');
INSERT INTO groups (name) VALUES ('AB-123');
INSERT INTO groups (name) VALUES ('CD-456');
INSERT INTO groups_students (group_id,student_id) VALUES(1,1);
INSERT INTO groups_students (group_id,student_id) VALUES(1,2);
INSERT INTO groups_students (group_id,student_id) VALUES(2,3);
INSERT INTO groups_students (group_id,student_id) VALUES(2,4);
INSERT INTO groups_students (group_id,student_id) VALUES(2,5);
INSERT INTO teachers (firstname, lastname) VALUES ('Jennie', 'Crigler');
INSERT INTO teachers (firstname, lastname) VALUES ('Gladys', 'Swon');
INSERT INTO courses (name, teacher) VALUES ('Science', 1);
INSERT INTO courses (name, teacher) VALUES ('Math', 2);
INSERT INTO classrooms (name) VALUES ('ROOM-15');
INSERT INTO classrooms (name) VALUES ('ROOM-20');
INSERT INTO lessons (group_id,course,classroom,starttime,duration) VALUES (1,1,1,1616510000000,2700000);
INSERT INTO lessons (group_id,course,classroom,starttime,duration) VALUES (2,2,2,1616510000000,3600000);