pipeline {
    agent any
    tools { 
		maven 'mvn' 
		jdk 'jdk11' 
	}
    stages {
        stage('Scan-package') { 
			steps {
				withSonarQubeEnv(credentialsId: 'jenkins-sonar-token', installationName:'sonar'){
					sh '''
					cd ./University
					mvn clean package sonar:sonar -Dstyle.color=never -DskipTests=true
					docker kill university
					docker rm university
					docker build -t university . -f ./dockerfiles/Dockerfile
					docker image prune -f
					cd ./dockerfiles					
					docker kill postgres
					docker kill keycloak
					docker rm postgres
					docker rm keycloak					
					/usr/bin/docker-compose up -d
					'''
				}
            }
		}
    }
}
